### ISSUE TITLE
상하의 트위스트 기능 목록 정의

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/sanghai_twist#1]
## 상하의 트위스트 기능 목록 정의

*상하의 트위스트*의 주요 기능은 **상-하의 매치 기능**이다.
이와 같이 앱에서 구현 해야할 상세 기능들 정의해보자.

**Comment by rkdgusrn1212** [comment]
## 답글 작성 규칙 

모두 생각나는 반드시 필요하다 싶은 상세 기능이 있다면 답글로 남겨주고, ~구현 가능성 확인을 위해~ 반드시 해당 기능을 기술적으로 구현할 방법도 대략 적어둘 것.

**Comment by rkdgusrn1212** [comment]
## 기능 1. 상-하의 매치 기능.

사용자가 임시저장 해둔 상의 이미지링크, 하의 이미지 링크를 통해 이미지들을 불러온 후, 사용자가 이미지들을 알맞게 크롭, 이미지를 위아래로 붙여서 한번에 볼수 있게 한다.

### 구현 상세

- 임시저장 : 브라우저 로컬 스토리지에 링크 저장
- 크롭 : 크롭 라이브러리 사용. ex) [cropperjs](https://github.com/fengyuanchen/cropperjs)

**Comment by rkdgusrn1212** [comment]
## 기능 2. 타 쇼핑몰 상품 검색 및 조회 기능. 

앱에서 사용자가 타 쇼핑몰의 상품을 검색하고 조회할수 있게 한다.

### 구현 상세

- 상품 데이터 : 11번가 Open API 사용. 추후 시간이 남으면 다른 쇼핑몰 상품의 Open API도 병합할 예정.
- API Key 때문에 서버 사이드 렌더링 or 클라이언트 대신 요청할 자체 서버 API 구축 필요.

**Comment by rkdgusrn1212** [comment]
## 기능 3. 옷장 기능 

[상-하의 매치 기능](https://github.com/rkdgusrn1212/sanghai_twist/issues/1#issuecomment-1338907875)을 사용하기 위한 필요조건으로 앱은 사용자가 구매, 혹은 상-하의 매치 기능사 용해 보기 위해 상품을 별도의 메모리에 임시 저장할 수 있다.

### 구현 상세

- 상품 저장 데이터 : Open Api 로 받은 상품의 키값 및 구조화된 모든 상세 데이터들.
- 저장할 메모리 : 브라우저의 local storage 사용. ~사용자 인증 기능이 없기 때문에~

**Comment by devInt42** [comment]
> ## 상하의 트위스트 기능 목록 정의
> _상하의 트위스트_의 주요 기능은 **상-하의 매치 기능**이다. 이와 같이 앱에서 구현 해야할 상세 기능들 정의해보자.



> ## 기능 1. 상-하의 매치 기능.
> 사용자가 임시저장 해둔 상의 이미지링크, 하의 이미지 링크를 통해 이미지들을 불러온 후, 사용자가 이미지들을 알맞게 크롭, 이미지를 위아래로 붙여서 한번에 볼수 있게 한다.
> 
> ### 구현 상세
> * 임시저장 : 브라우저 로컬 스토리지에 링크 저장
> * 크롭 : 크롭 라이브러리 사용. ex) [cropperjs](https://github.com/fengyuanchen/cropperjs)
ㄴ> Canvas2HTML 라이브러리를 통해 웹상에서 이미지 편집 가능

**Comment by rkdgusrn1212** [comment]
## 1208 회의 결과

- drag&drop기능은 @Withksy97 가 연구중이었으나 시간상 보류하고 UI 작업부터 한 후 가장 먼저 한가해진 사람에게 할당하기로 결정.
- 쇼핑몰 검색 기능은 사용 불가. https://github.com/rkdgusrn1212/sanghai_twist/issues/23#issuecomment-1341798960 참조
- 다만 조회는 사용가능. 사용자가 원하는 카테고리를 선택하여 해당 카테고리의 전체 상품을 보여주고 해당 상품의 상세정보를 띄워주는것은 가능.
