### ISSUE TITLE
기능4. Drag & Drop

### ISSUE THREAD

**Issue by Withksy97** [rkdgusrn1212/sanghai_twist#6]
상-하의 매치 기능을 유저가 보다 편리하게 이용할 수 있도록 옷장 기능에서 별도의 메모리에 저장된 상품을 자유롭게 Matching 시킬 수 있는 Drag & Drop 기능을 구현하고자 한다.

**구현 상세**

- 저장된 데이터 : 옷장 기능에서 Open API의 상품 관련 데이터들을 로컬에 저장시킨 데이터들
- Drag & Drop 기능 구현 : 드래그 관련 이벤트들을 사용해서 옷장 기능으로 불러온 이미지 리스트를 상-하의 매칭시키는 임의의 영역(UI)에 Drop할 수 있도록 구현

**Comment by rkdgusrn1212** [comment]
[기능 정의 이슈](https://github.com/rkdgusrn1212/sanghai_twist/issues/1) 여기에 코멘트로 달아주세요~

**Comment by rkdgusrn1212** [comment]
시간관계상 기능 제외, 프로젝트 종료.
