### ISSUE TITLE
Resize & Crop 기능 구현 가능성 확인 및 테스트

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/sanghai_twist#7]
## 기능 1. 상-하의 매치 기능.

사용자가 임시저장 해둔 상의 이미지링크, 하의 이미지 링크를 통해 이미지들을 불러온 후, 사용자가 이미지들을 알맞게 크롭, 이미지를 위아래로 붙여서 한번에 볼수 있게 한다.

### 구현 상세

- 임시저장 : 브라우저 로컬 스토리지에 링크 저장
- 크롭 : 크롭 라이브러리 사용. ex) [cropperjs](https://github.com/fengyuanchen/cropperjs)

_Originally posted by @rkdgusrn1212 in https://github.com/rkdgusrn1212/sanghai_twist/issues/1#issuecomment-1338907875_

위 기능에서 Resize&Crop 기능을 사용한다.  [cropperjs](https://github.com/fengyuanchen/cropperjs) 또는 기타 라이브러리들을 활용해 테스트 코드를 작성해보면서 구현 가능성을 확인해 볼 필요가 있다.

**Comment by devInt42** [comment]
블로그 참고해서 개발예정
https://gamsungcoding.tistory.com/entry/React-React%EB%A1%9C-%EC%9D%B4%EB%AF%B8%EC%A7%80-%ED%8E%B8%EC%A7%91%ED%81%AC%EB%A1%AD-%ED%95%98%EA%B8%B0

**Comment by devInt42** [comment]
-cropperjs 실패로 인한 대안 라이브러리
toast ui image editor
깃허브 주소 : https://www.npmjs.com/package/@toast-ui/react-image-editor
